site_name: MyDigiTwin architecture documentation 
theme:
  name: material
  custom_dir: material
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/custom.css  
plugins:
  - search
  - with-pdf:
      author: Héctor Cadavid
      output_path: ./MDT-arc42-architecture-draft.pdf
