@startuml
actor Client
' The only difference between actor
'and participant is the drawing
participant Server #99FF99
participant "NodeA \n(aggregator)" as NA
participant "NodeA Docker" as NAD
participant NodeB
participant NodeC


Client->Server: Store new task
Client->Server: Start new task
Server->NA: Launch central task
NA->Server: Pull image
NA->NAD: [[http://www.google.com container]] 

@enduml